### ISSUE TITLE
Cache issue

### ISSUE THREAD

**Issue by CyrilleB79** [addonFactory/instantTranslate#11]
Hi Beqa,

Here is an issue:

### STR:
1. Set the source language to auto, the target language to French and the swap language to English; also ensure that auto-swapping is checked.
2. Translate a French sentence, e.g. "NVDA est un lecteur d'écran formidable.".
3. Set the swap language to Italian.
4. Translate exactly the same French sentence as step 2.

### Actual result
At step 2. translation is made in English as expected ("NVDA is a great screen reader.").
At step 4. translation is made in English.

### Expected result
At step 4. translation is made in Italian.

### Additional information

When you cache the result, you should search in the cache with all the inputs that were used to make this translation, i.e. source, target, swap, allow auto-swapping, is auto-swapped, replace underscores.
If you search the cache with only source and target, you may end up with various results if the other options are changed.

**Comment by beqabeqa473** [comment]
Hi.
Is it a case with latest codebase?

**Comment by CyrilleB79** [comment]
Yes, this is the case with latest master, i.e. commit 4600532ab5b136a7acc22e4352708fe0c1234f74.

The issue is the following:
`translateAndCache` takes text, langFrom and langTo as parameters so these are the parameters of the cache. But the result of this function also depends on self.lang_swap which is used in the function. Thus, you'd better add lang_swap as a parameter of the function.
Since the function also uses self.autoSwap and self.replaceUnderscores, we have probably the same type of issue with this attributes.

Note: I have also edited the initial description to make more precise the STR (auto-swap checked).

**Comment by beqabeqa473** [comment]
Aah, ok, i understood.
I will fix that.
I started to rewrite this addon, but i paused for some time because of
lack of time.
I'll return to it soon.

On 8/3/22, Cyrille Bougot ***@***.***> wrote:
> Yes, this is the case with latest master, i.e. commit
> 4600532ab5b136a7acc22e4352708fe0c1234f74.
>
> The issue is the following:
> `translateAndCache` takes text, langFrom and langTo as parameters so these
> are the parameters of the cache. But the result of this function also
> depends on self.lang_swap which is used in the function. Thus, you'd better
> add lang_swap as a parameter of the function.
> Since the function also uses self.autoSwap and self.replaceUnderscores, we
> have probably the same type of issue with this attributes.
>
> Note: I have also edited the initial description to make more precise the
> STR (auto-swap checked).
>
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/beqabeqa473/instantTranslate/issues/11#issuecomment-1203670517
> You are receiving this because you commented.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by CyrilleB79** [comment]
Fixed in #12.
Closing.
