### ISSUE TITLE
Do not cache empty translation results

### ISSUE THREAD

**Issue by cary-rowen** [addonFactory/instantTranslate#16]
If the translation result is empty, don't cache it.

## Steps to reproduce
1. Disconnect from the Internet.
2. Try to translate a piece of text from one language to another.
3. Connect to the network.
4. Perform step (2).
## Actual Behavior
Perform  step (4), the translation result is empty.

## Expected Behavior
Perform step (4) to get the translation result.

**Comment by beqabeqa473** [comment]
fixed by #33
