### ISSUE TITLE
Multi-translation engine: Add Chinese mirror of Google Translate

### ISSUE THREAD

**Issue by cary-rowen** [addonFactory/instantTranslate#27]
Hi,

Since Google Translate is not available in China, the NVDA China community has created a google translate mirror, it would be nice if you could add that mirror to the add-on.

https://translate.googleapis.mirror.nvdadr.com

Thanks

**Comment by beqabeqa473** [comment]
I am personally against doing that.
Even if this is non-confidentional information, i don't want to use proxy non-controlled by me.

I could spawn my own proxy server is you tell which isp is not blocked by chinese firewall.

**Comment by cary-rowen** [comment]
Which server is convenient for you? I think most servers are fine. Maybe the closer the location is to China, the better the experience.

**Comment by cary-rowen** [comment]
Hello @beqabeqa473 

May I know why this Issue was closed?
Have you provided a proxy server?

Thanks
